### ISSUE TITLE
Add default files on installation 

### ISSUE THREAD

**Issue by MelanX** [TrojanerHD/Songrequestbot-Old#14]
You know exactly what I mean. We wanna have settings.json and secrets.json! Thanks Obama.

**Comment by TrojanerHD** [comment]
Since secrets.json is only necessary when you are going to deploy the bot, I will not provide that file by default

**Comment by TrojanerHD** [comment]
Is fixed in https://github.com/TrojanerHD/Songrequestbot/commit/0d974b127cf05928d5ae35d91e238f00c9a8cc2d: The new path is [home](https://en.wikipedia.org/wiki/Home_directory#Default_home_directory_per_operating_system)/Songrequestbot/settings.json and will be automatically generated on the first startup
